# Source: https://monpoc.net/MonpocListBuilder/js/modelData.js
# flake8: noqa

MONSTERS_DATA = [
    [
        "Cthugrosh",
        "Destroyers",
        "Lords of Cthul",
        6,
        8,
        "7+4",
        "Rng:3 5+3",
        "6+4",
        11,
        [
            ["Action: Sacrifice", 0],
            ["Action: Summon", 0],
            ["Action: Telekinesis", 0],
            ["High Mobility", 0],
        ],
        [
            [
                "Hyper Cthugrosh",
                "Destroyers",
                "Lords of Cthul",
                6,
                8,
                "8+5",
                "Rng:5 5+4",
                "7+4",
                5,
                [
                    ["Action: Summon", 0],
                    ["Action: Telekinesis", 0],
                    ["Fling", 2],
                    ["High Mobility", 0],
                    ["Terrify", 0],
                ],
            ]
        ],
    ],
    [
        "Yasheth",
        "Destroyers",
        "Lords of Cthul",
        6,
        8,
        "7+3",
        "-",
        "6+4",
        11,
        [["High Mobility", 0], ["Penetrator", 1], ["Side Step", 0], ["Vampirism", 1]],
        [
            [
                "Hyper Yasheth",
                "Destroyers",
                "Lords of Cthul",
                7,
                9,
                "8+5",
                "-",
                "6+5",
                5,
                [
                    ["Arcane Void", 0],
                    ["High Mobility", 0],
                    ["Lightning Attack", 0],
                    ["Penetrator", 0],
                    ["Siphon", 0],
                ],
            ]
        ],
    ],
    [
        "Ares Mothership",
        "Destroyers",
        "Martian Menace",
        7,
        8,
        "6+3",
        "Rng:3 6+4",
        "5+4",
        11,
        [
            ["Action: Abduct (4)", 0],
            ["Action: Transport", 0],
            ["Flight", 0],
            ["High Mobility", 0],
            ["Manufacture", 1],
            ["Mechanical", 0],
            ["Steady", 0],
        ],
        [
            [
                "Hyper Ares Mothership",
                "Destroyers",
                "Martian Menace",
                7,
                8,
                "6+4",
                "Rng:5 6+5",
                "5+4",
                5,
                [
                    ["Flight", 0],
                    ["High Mobility", 0],
                    ["Hit & Run", 2],
                    ["Manufacture", 1],
                    ["Mechanical", 0],
                    ["Spotter", 0],
                    ["Steady", 0],
                    ["Tactical Command", 0],
                ],
            ]
        ],
    ],
    [
        "Deimos-9",
        "Destroyers",
        "Martian Menace",
        6,
        8,
        "7+4",
        "Rng:3 4+3",
        "6+4",
        11,
        [["Flank", 0], ["Grappler", 0], ["Mechanical", 0], ["Power Gorge", 2]],
        [
            [
                "Hyper Deimos-9",
                "Destroyers",
                "Martian Menace",
                6,
                8,
                "8+5",
                "Rng:3 4+4",
                "7+5",
                5,
                [
                    ["Energy Cycle", 0],
                    ["Flank", 0],
                    ["Fling", 1],
                    ["Grappler", 0],
                    ["Lightning Attack", 0],
                    ["Mechanical", 0],
                ],
            ]
        ],
    ],
    [
        "Gorghadra",
        "Destroyers",
        "Planet Eaters",
        6,
        8,
        "8+4",
        "Rng:3 4+4",
        "7+4",
        11,
        [["Chain Reaction", 1], ["Demolisher", 0], ["Disintegrate", 2], ["Riled", 0]],
        [
            [
                "Hyper Gorghadra",
                "Destroyers",
                "Planet Eaters",
                6,
                9,
                "9+5",
                "Rng:3 5+5",
                "8+5",
                5,
                [
                    ["Annhilate", 0],
                    ["Chain Reaction", 1],
                    ["Demolisher", 0],
                    ["Disintegrate", 2],
                    ["Riled", 0],
                    ["Unearthly Rage", 0],
                ],
            ]
        ],
    ],
    [
        "Rogzor",
        "Destroyers",
        "Planet Eaters",
        6,
        8,
        "6+3",
        "Rng:5 6+4",
        "5+3",
        10,
        [["Devastation", 0], ["High Impact", 0], ["Penetrator", 0]],
        [
            [
                "Hyper Rogzor",
                "Destroyers",
                "Planet Eaters",
                7,
                8,
                "6+4",
                "Rng:5 8+6",
                "5+4",
                5,
                [
                    ["Beat Back", 0],
                    ["Devastation", 0],
                    ["High Impact", 0],
                    ["Penetrator", 0],
                    ["Return Fire", 0],
                ],
            ]
        ],
    ],
    [
        "Hammerklak",
        "Destroyers",
        "Subterran Uprising",
        7,
        8,
        "6+4",
        "-",
        "6+4",
        10,
        [
            ["Action: Sprint", 0],
            ["Cloak", 0],
            ["Crunch", 0],
            ["High Mobility", 0],
            ["Side Step", 0],
            ["Tunneler", 0],
        ],
        [
            [
                "Hyper Hammerklak",
                "Destroyers",
                "Subterran Uprising",
                7,
                9,
                "9+6",
                "-",
                "9+6",
                5,
                [
                    ["Action: Sprint", 0],
                    ["Crunch", 0],
                    ["Energy Cycle", 0],
                    ["High Mobility", 0],
                    ["Power Gorge", 1],
                    ["Power Gorge", 3],
                ],
            ]
        ],
    ],
    [
        "Cyber Khan",
        "Destroyers",
        "UberCorp International",
        6,
        8,
        "6+3",
        "Rng:5 7+4",
        "6+4",
        11,
        [
            ["Destabilizer", 0],
            ["High Mobility", 0],
            ["Mechanical", 0],
            ["Power Drain", 2],
            ["Seismic Step", 0],
            ["Strip Mining", 0],
        ],
        [
            [
                "Hyper Cyber Khan",
                "Destroyers",
                "UberCorp International",
                6,
                8,
                "7+4",
                "Rng:5 8+5",
                "7+5",
                5,
                [
                    ["Demolisher", 0],
                    ["High Mobility", 0],
                    ["Mechanical", 0],
                    ["Penetrator", 3],
                    ["Rapid Fire", 0],
                    ["Siphon", 2],
                    ["Spotter", 0],
                ],
            ]
        ],
    ],
    [
        "General Hondo",
        "Protectors",
        "Empire of the Apes",
        5,
        8,
        "6+3",
        "Rng:5 7+4",
        "6+3",
        10,
        [
            ["Armored", 0],
            ["Defense Array", 0],
            ["Explosion", 2],
            ["Guerrilla Tactics", 0],
            ["Indirect Fire", 2],
        ],
        [
            [
                "Hyper General Hondo",
                "Protectors",
                "Empire of the Apes",
                6,
                8,
                "7+5",
                "Rng:5 8+5",
                "7+5",
                5,
                [
                    ["Energy Cycle", 0],
                    ["Explosion", 2],
                    ["High Impact", 0],
                    ["Indirect Fire", 2],
                    ["Rapid Fire", 0],
                ],
            ]
        ],
    ],
    [
        "King Kondo",
        "Protectors",
        "Empire of the Apes",
        6,
        8,
        "7+4",
        "-",
        "6+4",
        11,
        [
            ["Blood Rage", 0],
            ["Demolition", 1],
            ["Grappler", 0],
            ["High Mobility", 0],
            ["Tantrum", 0],
        ],
        [
            [
                "Hyper King Kondo",
                "Protectors",
                "Empire of the Apes",
                6,
                8,
                "9+6",
                "-",
                "8+5",
                6,
                [
                    ["Blood Rage", 0],
                    ["Demolition", 1],
                    ["Grappler", 0],
                    ["High Mobility", 0],
                    ["Riled", 0],
                    ["Weapon Master", 1],
                ],
            ]
        ],
    ],
    [
        "Defender X",
        "Protectors",
        "G.U.A.R.D.",
        6,
        8,
        "7+4",
        "Rng:3 7+4",
        "5+4",
        11,
        [["Disruption", 0], ["High Mobility", 0], ["Mechanical", 0], ["Safeguard", 0]],
        [
            [
                "Hyper Defender X",
                "Protectors",
                "G.U.A.R.D.",
                6,
                8,
                "7+5",
                "Rng:3 7+5",
                "6+4",
                5,
                [
                    ["Beat Back", 2],
                    ["Disruption", 0],
                    ["Energy Cycle", 0],
                    ["High Mobility", 0],
                    ["Mechanical", 0],
                    ["Safeguard", 0],
                ],
            ]
        ],
    ],
    [
        "Sky Sentinel",
        "Protectors",
        "G.U.A.R.D.",
        7,
        9,
        "6+3",
        "Rng:5 6+4",
        "5+3",
        11,
        [
            ["Anti-Air", 0],
            ["Flight", 0],
            ["High Mobility", 0],
            ["Mechanical", 0],
            ["Wing Leader", 0],
        ],
        [
            [
                "Hyper Sky Sentinel",
                "Protectors",
                "G.U.A.R.D.",
                7,
                9,
                "6+4",
                "Rng:5 7+5",
                "5+4",
                5,
                [
                    ["Flight", 0],
                    ["High Mobility", 0],
                    ["Mechanical", 0],
                    ["Power Gorge", 2],
                    ["Rapid Fire", 0],
                    ["Wing Leader", 0],
                ],
            ]
        ],
    ],
    [
        "Zor-Maxim",
        "Protectors",
        "Shadow Sun Syndicate",
        7,
        9,
        "7+4",
        "-",
        "7+3",
        10,
        [
            ["Action: Teleport", 0],
            ["High Mobility", 0],
            ["Penetrator", 3],
            ["Side Step", 0],
        ],
        [
            [
                "Hyper Zor-Maxim",
                "Protectors",
                "Shadow Sun Syndicate",
                7,
                10,
                "7+5",
                "Rng:3 6+4",
                "8+5",
                5,
                [
                    ["Action: Teleport", 0],
                    ["Energy Cycle", 0],
                    ["High Mobility", 0],
                    ["Penetrator", 3],
                    ["Rapid Fire", 0],
                ],
            ]
        ],
    ],
    [
        "Zor-Raiden",
        "Protectors",
        "Shadow Sun Syndicate",
        7,
        9,
        "8+4",
        "-",
        "6+4",
        10,
        [
            ["Combat Coordination", 0],
            ["High Mobility", 0],
            ["Hit & Run", 1],
            ["Reposition", 0],
        ],
        [
            [
                "Hyper Zor-Raiden",
                "Protectors",
                "Shadow Sun Syndicate",
                7,
                9,
                "8+6",
                "Rng:3 4+4",
                "7+4",
                5,
                [
                    ["Combat Coordination", 0],
                    ["Flank", 0],
                    ["High Mobility", 0],
                    ["Hit & Run", 1],
                    ["Reposition", 0],
                    ["Weapon Master", 1],
                ],
            ]
        ],
    ],
    [
        "Armodax",
        "Protectors",
        "Terrasaurs",
        6,
        7,
        "7+4",
        "-",
        "6+4",
        12,
        [["Armored", 0], ["Demolisher", 0], ["Power Gorge", 1], ["Resilience", 0]],
        [
            [
                "Hyper Armodax",
                "Protectors",
                "Terrasaurs",
                6,
                8,
                "8+5",
                "-",
                "7+5",
                6,
                [
                    ["Armored", 0],
                    ["Beat Back", 1],
                    ["Resilience", 0],
                    ["Riled", 0],
                    ["Unearthly Rage", 0],
                ],
            ]
        ],
    ],
    [
        "Terra Khan",
        "Protectors",
        "Terrasaurs",
        6,
        8,
        "8+4",
        "Rng:5 5+3",
        "6+4",
        11,
        [["Feeding Frenzy", 0], ["Munch", 1], ["Stampede", 0]],
        [
            [
                "Hyper Terra Khan",
                "Protectors",
                "Terrasaurs",
                8,
                8,
                "9+6",
                "Rng:3 7+4",
                "7+5",
                5,
                [
                    ["Blood Rage", 0],
                    ["Explosion", 2],
                    ["Feeding Frenzy", 0],
                    ["Lightning Attack", 0],
                ],
            ]
        ],
    ],
    [
        "Krakenoctus",
        "Protectors",
        "Tritons",
        5,
        9,
        "8+4",
        "-",
        "7+4",
        12,
        [
            ["Fling", 1],
            ["Grappler", 0],
            ["Lightning Attack", 0],
            ["Reach", 0],
            ["Waterlogged", 0],
        ],
        [
            [
                "Hyper Krakenoctus",
                "Protectors",
                "Tritons",
                5,
                9,
                "9+5",
                "Rng:3 5+4",
                "8+5",
                6,
                [
                    ["Fling", 1],
                    ["Grappler", 0],
                    ["Power Drain", 2],
                    ["Reach", 0],
                    ["Slingshot", 0],
                    ["Waterlogged", 0],
                    ["Windup", 0],
                ],
            ]
        ],
    ],
]
UNITS_DATA = [
    [
        "Meat Slave",
        "Destroyers",
        "Lords of Cthul",
        4,
        2,
        "-",
        "-",
        "2",
        [["Incubator", 0]],
    ],
    [
        "Spitter",
        "Destroyers",
        "Lords of Cthul",
        4,
        3,
        "-",
        "Rng:5 1+1",
        "1",
        [["Action: Extinguisher", 0], ["All Terrain", 0]],
    ],
    [
        "Spitter Elite",
        "Destroyers",
        "Lords of Cthul",
        4,
        3,
        "-",
        "Rng:5 1+2",
        "2",
        [["Action: Extinguisher", 0], ["All Terrain", 0], ["Commander", 0]],
    ],
    [
        "Squix",
        "Destroyers",
        "Lords of Cthul",
        6,
        2,
        "1+1",
        "Rng:3 2+0",
        "1",
        [["Disruption", 0], ["Flight", 0], ["High Mobility", 0]],
    ],
    [
        "Squix Elite",
        "Destroyers",
        "Lords of Cthul",
        6,
        2,
        "1+2",
        "Rng:3 2+1",
        "2",
        [["Commander", 0], ["Disruption", 0], ["Flight", 0], ["High Mobility", 0]],
    ],
    [
        "Task Master",
        "Destroyers",
        "Lords of Cthul",
        5,
        4,
        "3+2",
        "-",
        "2",
        [["Fling", 1], ["Action: Telekinesis", 0], ["Motivator", 0]],
    ],
    [
        "Hunter",
        "Destroyers",
        "Martian Menace",
        6,
        2,
        "-",
        "Rng:5 2+2",
        "2",
        [["Flight", 0], ["High Mobility", 0], ["Lone Wolf", 0], ["Penetrator", 0]],
    ],
    [
        "Power Pod",
        "Destroyers",
        "Martian Menace",
        2,
        2,
        "-",
        "-",
        "1",
        [["All Terrain", 0], ["Amplify", 0], ["Cargo", 0]],
    ],
    [
        "Saucer",
        "Destroyers",
        "Martian Menace",
        5,
        2,
        "-",
        "-",
        "1",
        [
            ["Action: Abduct (2)", 0],
            ["Action: Transport", 0],
            ["Flight", 0],
            ["High Mobility", 0],
        ],
    ],
    [
        "Vanguard",
        "Destroyers",
        "Martian Menace",
        6,
        1,
        "-",
        "Rng:3 1+1",
        "1",
        [["Destabilizer", 0], ["Disintegrate", 0], ["Flight", 0], ["High Mobility", 0]],
    ],
    [
        "Vanguard Elite",
        "Destroyers",
        "Martian Menace",
        6,
        1,
        "-",
        "Rng:3 1+2",
        "2",
        [
            ["Commander", 0],
            ["Destabilizer", 0],
            ["Disintegrate", 0],
            ["Flight", 0],
            ["High Mobility", 0],
        ],
    ],
    [
        "Belcher",
        "Destroyers",
        "Planet Eaters",
        4,
        2,
        "1+0",
        "Rng:5 2+1",
        "1",
        [["Indirect Fire", 0]],
    ],
    [
        "Belcher Elite",
        "Destroyers",
        "Planet Eaters",
        4,
        2,
        "1+1",
        "Rng:5 2+2",
        "2",
        [["Commander", 0], ["Indirect Fire", 0]],
    ],
    [
        "Chomper",
        "Destroyers",
        "Planet Eaters",
        5,
        3,
        "2+2",
        "-",
        1,
        [["Power Gorge", 1]],
    ],
    [
        "Chomper Elite",
        "Destroyers",
        "Planet Eaters",
        5,
        3,
        "2+3",
        "-",
        2,
        [["Power Gorge", 1], ["Commander", 0]],
    ],
    [
        "Crawler",
        "Destroyers",
        "Planet Eaters",
        4,
        4,
        "-",
        "-",
        1,
        [["All Terrain", 0], ["Burrower", 0], ["Dig In", 0], ["Unstable", 0]],
    ],
    [
        "Destructomite",
        "Destroyers",
        "Planet Eaters",
        6,
        2,
        "3+1",
        "-",
        1,
        [["All Terrain", 0], ["Flank", 0]],
    ],
    [
        "Explodohawk",
        "Destroyers",
        "Planet Eaters",
        6,
        1,
        "6+3",
        "-",
        1,
        [
            ["Chain Reaction", 1],
            ["High Mobility", 0],
            ["Flight", 0],
            ["Lone Wolf", 0],
            ["Self-Destruct", 0],
        ],
    ],
    [
        "Carnitron",
        "Destroyers",
        "UberCorp International",
        4,
        3,
        "2+1",
        "Rng:3 1+0",
        "1",
        [["Dual Attack", 0]],
    ],
    [
        "Carnitron Elite",
        "Destroyers",
        "UberCorp International",
        4,
        3,
        "2+2",
        "Rng:3 1+1",
        "2",
        [["Commander", 0], ["Dual Attack", 0]],
    ],
    [
        "Robo Brontox",
        "Destroyers",
        "UberCorp International",
        4,
        4,
        "1+1",
        "-",
        "2",
        [["Feedback", 0], ["Intensify", 0], ["Jam", 0]],
    ],
    [
        "Shinobot",
        "Destroyers",
        "UberCorp International",
        5,
        3,
        "2+1",
        "-",
        "1",
        [["Action: Sprint", 0], ["High Mobility", 0]],
    ],
    [
        "Shinobot Elite",
        "Destroyers",
        "UberCorp International",
        5,
        3,
        "2+2",
        "-",
        "2",
        [["Action: Sprint", 0], ["Commander", 0], ["High Mobility", 0]],
    ],
    [
        "Shinobot Gunner",
        "Destroyers",
        "UberCorp International",
        5,
        2,
        "1",
        "Rng:3 2+2",
        "2",
        [["Explosion", 2], ["High Mobility", 0]],
    ],
    [
        "Uber Jet",
        "Destroyers",
        "UberCorp International",
        6,
        1,
        "-",
        "Rng:3 1+1",
        "2",
        [
            ["Action: Teleport", 0],
            ["Flight", 0],
            ["Force Field", 0],
            ["High Mobility", 0],
            ["Shield Resonance", 0],
        ],
    ],
    [
        "Ape Gunner",
        "Protectors",
        "Empire of the Apes",
        5,
        2,
        "2+1",
        "Rng:5 2+1",
        "1",
        [["All Terrain", 0]],
    ],
    [
        "Ape Gunner Elite",
        "Protectors",
        "Empire of the Apes",
        5,
        2,
        "2+2",
        "Rng:5 2+2",
        "2",
        [["All Terrain", 0], ["Commander", 0]],
    ],
    [
        "Ape Infiltrator",
        "Protectors",
        "Empire of the Apes",
        6,
        2,
        "1+1",
        "-",
        "1",
        [["Cloak", 0], ["Forward Observer", 0], ["High Mobility", 0], ["Spotter", 0]],
    ],
    [
        "Assault Ape",
        "Protectors",
        "Empire of the Apes",
        4,
        3,
        "2+1",
        "-",
        "1",
        [["Fling", 1], ["High Mobility", 0], ["Power Hitter", 0]],
    ],
    [
        "Assault Ape Elite",
        "Protectors",
        "Empire of the Apes",
        4,
        3,
        "2+2",
        "-",
        "2",
        [["Commander", 0], ["Fling", 1], ["High Mobility", 0], ["Power Hitter", 0]],
    ],
    [
        "Rocket Ape",
        "Protectors",
        "Empire of the Apes",
        5,
        2,
        "1+0",
        "Rng:5 2+2",
        "2",
        [["Aim", 0], ["Lone Wolf", 0], ["Multi-Fire", 2]],
    ],
    [
        "G-Tank",
        "Protectors",
        "G.U.A.R.D.",
        4,
        4,
        "1+0",
        "Rng:5 2+0",
        "1",
        [["Aim", 0], ["All Terrain", 0]],
    ],
    [
        "G-Tank Elite",
        "Protectors",
        "G.U.A.R.D.",
        4,
        4,
        "1+1",
        "Rng:5 2+1",
        "2",
        [["Aim", 0], ["All Terrain", 0], ["Commander", 0]],
    ],
    [
        "Repair Truck",
        "Protectors",
        "G.U.A.R.D.",
        5,
        2,
        "-",
        "-",
        1,
        [["Action: Repair", 0]],
    ],
    [
        "Rocket Chopper",
        "Protectors",
        "G.U.A.R.D.",
        5,
        2,
        "-",
        "Rng:3 2+1",
        "1",
        [["Flight", 0], ["High Mobility", 0], ["Spotter", 0]],
    ],
    [
        "Strike Fighter",
        "Protectors",
        "G.U.A.R.D.",
        7,
        1,
        "-",
        "Rng:3 2+1",
        "1",
        [["Flight", 0], ["High Mobility", 0], ["Indirect Fire", 0]],
    ],
    [
        "Strike Fighter Elite",
        "Protectors",
        "G.U.A.R.D.",
        7,
        1,
        "-",
        "Rng:3 2+2",
        "2",
        [["Commander", 0], ["Flight", 0], ["High Mobility", 0], ["Indirect Fire", 0]],
    ],
    [
        "Interceptor",
        "Protectors",
        "Shadow Sun Syndicate",
        6,
        3,
        "-",
        "Rng:3 1+0",
        "1",
        [["Action: Overdrive", 0], ["Action: Transport", 0], ["All Terrain", 0]],
    ],
    [
        "S-Type Shinobi",
        "Protectors",
        "Shadow Sun Syndicate",
        5,
        3,
        "2+1",
        "-",
        "1",
        [["Cloak", 0], ["High Mobility", 0], ["Side Step", 0]],
    ],
    [
        "S-Type Shinobi Elite",
        "Protectors",
        "Shadow Sun Syndicate",
        5,
        3,
        "2+2",
        "-",
        "2",
        [["Cloak", 0], ["Commander", 0], ["High Mobility", 0], ["Side Step", 0]],
    ],
    [
        "Shadow Gate",
        "Protectors",
        "Shadow Sun Syndicate",
        3,
        2,
        "-",
        "-",
        "1",
        [
            ["Action: Teleport", 0],
            ["All Terrain", 0],
            ["Cargo", 0],
            ["Cloak", 0],
            ["Shadow Field", 0],
        ],
    ],
    [
        "Sun Fighter",
        "Protectors",
        "Shadow Sun Syndicate",
        7,
        2,
        "-",
        "Rng:5 2+0",
        "1",
        [["Anti-Air", 0], ["Flight", 0], ["High Mobility", 0]],
    ],
    [
        "Sun Fighter Elite",
        "Protectors",
        "Shadow Sun Syndicate",
        7,
        2,
        "-",
        "Rng:5 2+1",
        "2",
        [["Anti-Air", 0], ["Commander", 0], ["Flight", 0], ["High Mobility", 0]],
    ],
    [
        "Brontox",
        "Protectors",
        "Terrasaurs",
        4,
        4,
        "1+1",
        "-",
        "2",
        [["Action: Nesting", 0], ["Dig In", 0]],
    ],
    ["Carnidon", "Protectors", "Terrasaurs", 4, 3, "2+2", "-", "1", []],
    [
        "Carnidon Elite",
        "Protectors",
        "Terrasaurs",
        4,
        3,
        "2+2",
        "-",
        "2",
        [["Commander", 0], ["Flank", 0]],
    ],
    [
        "Raptix",
        "Protectors",
        "Terrasaurs",
        6,
        2,
        "1+1",
        "-",
        "1",
        [["Anti-Air", 0], ["High Mobility", 0]],
    ],
    [
        "Raptix Elite",
        "Protectors",
        "Terrasaurs",
        6,
        2,
        "1+2",
        "-",
        "2",
        [["Anti-Air", 0], ["Commander", 0], ["High Mobility", 0]],
    ],
    [
        "Spikodon",
        "Protectors",
        "Terrasaurs",
        4,
        3,
        "1+0",
        "Rng:4 2+2",
        "2",
        [["Explosion", 0]],
    ],
]
BUILDINGS_DATA = [
    ["Apartment Building", "", "", "Building", 5, [["High Density", 0]]],
    [
        "Communications Array",
        "",
        "",
        "Building",
        6,
        [["Incombustable", 0], ["Radar Network", 0]],
    ],
    [
        "Corporate Headquarters",
        "",
        "",
        "Building",
        6,
        [["Intel", 0], ["Trade Policy", 0]],
    ],
    [
        "Downtown Highrise",
        "",
        "",
        "Building",
        6,
        [["High Occupancy", 0], ["Security Building", 0]],
    ],
    [
        "G.U.A.R.D. Defense Base",
        "",
        "",
        "Building",
        7,
        [
            ["Action: Command & Control", 0],
            ["G.U.A.R.D. Base", 0],
            ["Incombustable", 0],
        ],
    ],
    [
        "Harbinger Comet Shard",
        "",
        "",
        "Building",
        7,
        [["Planet Eaters Base", 0], ["Power Converter", 0]],
    ],
    ["Imperial State Building", "", "", "Building", 7, [["Action: City Planning", 0]]],
    ["Industrial Complex", "", "", "Building", 6, [["Fuel Depot", 0]]],
    [
        "Jungle Fortress",
        "",
        "",
        "Building",
        7,
        [["Action: Patrol Base", 0], ["Empire of the Apes Base", 0]],
    ],
    [
        "Martian Command Post",
        "",
        "",
        "Building",
        7,
        [["Martian Menace Base", 0], ["Resource Domination", 0]],
    ],
    [
        "Mount Terra",
        "",
        "",
        "Building",
        7,
        [["Action: Tectonic Shift", 0], ["Terrasaurs Base", 0]],
    ],
    [
        "Power Plant",
        "",
        "",
        "Building",
        6,
        [
            ["Blast Radius", 0],
            ["Electrical Node", 0],
            ["Incombustable", 0],
            ["Power Producer", 0],
        ],
    ],
    ["Skyscraper", "", "", "Building", 7, [["Discount", 0]]],
    [
        "Statue of Liberty",
        "",
        "",
        "Building",
        6,
        [["Incombustable", 0], ["Opportunity", 0]],
    ],
    [
        "Sun Industries Building",
        "",
        "",
        "Building",
        7,
        [
            ["Shadow Screen", 0],
            ["Shadow Sun Syndicate Base", 0],
            ["Underground Network", 0],
        ],
    ],
    [
        "The Tokyo Tower",
        "",
        "",
        "Building",
        6,
        [
            ["Action: Tourism Campaign", 0],
            ["Incombustable", 0],
            ["Spire", 0],
            ["Vantage Point", 0],
        ],
    ],
    [
        "Void Gate",
        "",
        "",
        "Building",
        7,
        [
            ["Action: Empower", 0],
            ["Action: Psychokinesis", 0],
            ["Lords of Cthul Base", 0],
        ],
    ],
]
ABILITIES_DATA = [
    [
        "Action: Abduct (2)",
        "This model can spend one Action Die to perform an Abduct action during its Activation. If this model is adjacent to an enemy unit with DEF 2 or less, return the enemy unit to your opponent's unit reserves.",
    ],
    [
        "Action: Abduct (4)",
        "This model can spend one Action Die to perform an Abduct action during its Activation. If this model is adjacent to an enemy unit with DEF 4 or less, return the enemy unit to your opponent's unit reserves.",
    ],
    [
        "Action: City Planning",
        "During your Monster or Unit Activation, this model can spend one Action Die to perform an Urban Renewal action. Swap the position of a building you are securing with any unsecured building on the map.",
    ],
    [
        "Action: Command & Control",
        "If you make an attack that fails to hit during your Unit or Monster Activation, this model can spend one Action Die to perform a Command & Control action. Reroll that attack roll.",
    ],
    [
        "Action: Empower",
        "During your Unit or Monster Activation, this model can spend one Action Die to perform an Empower action. Replace one allied grunt unit with an elite unit of the same type from your unit reserves.",
    ],
    [
        "Action: Extinguisher",
        "During this model's Activation, this model can spend one Action Die while adjacent to a debris tile to perform an Extinguisher action. If the tile is a hazard, flip it to the rubble side.",
    ],
    [
        "Action: Nesting",
        "This unit can spend one Action Die to perform a Nesting action if it is holding a power zone or negative zone during your unit activation. Choose any Faction unit from your unit reserves and place it in play adjacent to this model. The placed model cannot advance this turn.",
    ],
    [
        "Action: Overdrive",
        "During this model's activation, this model can spend one Action Die to perform an Overdrive Action. Advance this model up to its SPD, even if it has already advanced this turn.",
    ],
    [
        "Action: Patrol Base",
        "During your unit Activation, this model can spend one Action Die to perform a Patrol Base action. Choose one unit from your unit reserves and place it in play adjacent to this model. The placed model cannot advance this turn.",
    ],
    [
        "Action: Psychokinesis",
        "During your Unit or Monster Activation, this model can spend one Action Die to perform a Psychokinesis action. Choose one unit within three spaces of this model. Move the chosen unit one space.",
    ],
    [
        "Action: Repair",
        "During this model's Activation, this model can spend one Action Die while adjacent to a debris pile to perform a Repair action. If the tile is a hazard, flip it to the rubble side. if the tile is rubble and unoccupied, remove it and return a destroyed building to play on that foundation.",
    ],
    [
        "Action: Sacrifice",
        "During this model's Activation, this model can spend one Action Die to perform a Sacrifice action. Destroy one adjacent allied unit to restore one point of health to this monster.",
    ],
    [
        "Action: Sprint",
        "During your Monster Activation, this model can spend one Action Die to perform a Sprint action. Advance this model up to three spaces, even if it has already advanced this turn.",
    ],
    [
        "Action: Summon",
        "During this model's Activation, this model can spend one Action Die to perform a Summon action. Take one Faction unit from your unit reserves and place it in play adjacent to this model.",
    ],
    [
        "Action: Tectonic Shift",
        "During your Unit or Monster Activation, this model can spend one Action Die to perform a Tectonic Shift action. Advance one of your monsters up to two spaces.",
    ],
    [
        "Action: Telekinesis",
        "During this model's Activation, this model can spend one Action Die to perform a Telekinesis action. Choose one unit within two spaces of this model. Move the chosen unit one space.",
    ],
    [
        "Action: Teleport",
        "During this model's Activation, this model can spend one Action Die to perform a Teleport action. Either choose an adjacent allied unit and place it adjacent to another allied model with Teleport or choose one allied unit adjacent to another allied model with Teleport and place it adjacent to this model.",
    ],
    [
        "Action: Tourism Campaign",
        "During your Unit Activation, this model can spend on Action Die to perform a Tourism Campaign action. Gain one Power Die..",
    ],
    [
        "Action: Transport",
        "During this model's activation, this model can spend one Action Die to perform a Transport action. Take one allied unit with the Cargo special rule from your unit reserves and place it play adjacent to this model.",
    ],
    [
        "Aim",
        "This model gains +1 Boost Die when particiapating in blast attacks if it did not advance this activation.",
    ],
    ["All Terrain", "This model treats rough terrain as open terrain while advancing."],
    [
        "Amplify",
        "If one or more allied units with Amplify are holding power zones when you Power Up, gain one additional Power Die.",
    ],
    ["Annhilate", "This monster's attacks do super damage."],
    [
        "Anti-Air",
        "This model gains +1 Boost Die when participating in brawl or blast attacks targeting a model with Flight.",
    ],
    [
        "Arcane Void",
        "While this model is in play, allied units' blast and brawl attacks gain Siphon.",
    ],
    ["Armored", "This monster is immune to damage from collisions with buildings."],
    [
        "Beat Back",
        "If this model hits an enemy monster with this attack, after the attack is resolved you can move the monster hit up to two spaces in a straight line in any direction. During this movement, the target monster moves through and collides with buildings, units, and hazards in its path. The target monster stops moving if it collides with another monster.",
    ],
    [
        "Blast Radius",
        "If this model is destroyed, return all units adjacent to it to their unit reserves.",
    ],
    [
        "Blood Rage",
        "While this model is in play, allied Faction units gain +1 Boost Die when participating in Brawl attacks.",
    ],
    ["Burrower", "This model is immune to swat attacks."],
    ["Cargo", "This unit is cargo."],
    [
        "Chain Reaction",
        "If this attack hits a unit, all units adjacent to the target unit with DEF equal to or less than the number of strikes rolled also suffer 1 damage point as a result of this attack.",
    ],
    [
        "Cloak",
        "This model cannot be targeted by blast attacks made by a model more than two spaces away.",
    ],
    [
        "Combat Coordination",
        "While this model is in play, allied Faction units' brawl attacks gain the Hit & Run special rule.",
    ],
    [
        "Commander",
        "Allied same-named grunt units within two spaces of this unit gain +1 Boost Die when participating in brawl or blast attacks.",
    ],
    [
        "Crunch",
        "When you roll a super strike on an Action Die on one of this monster's attack rolls, that attack does super damage.",
    ],
    [
        "Defense Array",
        "Allied Faction units gain Force Field while within 3 spaces of this model. (A model with Force Field gains +1 DEF against blast attacks.)",
    ],
    [
        "Demolisher",
        "When this model makes an attack, gain +1 Power Die for every building destroyed as a result of its attack.",
    ],
    [
        "Demolition",
        "If this attack his a building, all units adjacent to the target building with a DEF equal to of less than the number of strikes rolled suffer 1 damage point as a result of this attack.",
    ],
    [
        "Destabilizer",
        "This model gains +1 Boost Die when participating in brawl or blast attacks that target a building.",
    ],
    [
        "Devastation",
        "If this attack his a building, all units adjacent to the target building with a DEF equal to of less than the number of strikes rolled suffer 1 damage point as a result of this attack. When determining the DEF of adjacent models, add any bonuses to DEF against blast attacks, including cover.",
    ],
    [
        "Dig In",
        "This model gains Cover while it is holding a power zone or negative zone.",
    ],
    [
        "Discount",
        "Once per turn, if you are securing one or more buildings with Discount and spawn a unit, reduce its Cost by 1.",
    ],
    [
        "Disintegrate",
        "Buildings destroyed by this attack are not replaced by rubble or hazards.",
    ],
    [
        "Disruption",
        "Enemy models attacking while within two spaces of this model lose one Boost Die on their attack rolls.",
    ],
    [
        "Dual Attack",
        "This model can participate in a brawl attack in addition to any other attack it participates in during each of your Unit Activations.",
    ],
    [
        "Electrical Node",
        "If a mechanical monster destroys this model with a brawl attack, after the attack is resolved restore one point of health to the monster. ",
    ],
    [
        "Empire of the Apes Base",
        "Once per turn, if you are securing one or more buildings with Empire of the Apes Base and spawn a Empire of the Apes unit, reduce its cost by 1.",
    ],
    [
        "Energy Cycle",
        "If you roll two or more Action Dice on an attack made by this model and the attack hits an enemy model, after the attack is resolved you can move one Action Die from your Unit Pool to your Monster Pool.",
    ],
    [
        "Explosion",
        "If this attack hits a unit, all units adjacent to the target unit with a DEF equal to or less than the number of strikes rolled also suffer 1 damage point as a result of this attack. When determining the DEF of adjacent models, add any bonuses to DEF against blast attacks, including cover.",
    ],
    [
        "Feedback",
        "If this model is destroyed by an adjacent monster, you gain one Power Die. That monster's controller loses one Power Die.",
    ],
    [
        "Feeding Frenzy",
        "When this monster attacks a monster that is adjacent to any allied Faction unit, this model's attack does Super Damage.",
    ],
    [
        "Flank",
        "Enemies withing two spaces of this model have their DEF reduced by 1 against brawl attacks made by allied models, to a minimum of 1.",
    ],
    [
        "Flight",
        "This model can end its movement on impassable terrain and is immune to hazards except when colliding with them.",
    ],
    [
        "Fling",
        "When this attack hits a unit, choose a building or enemy model within five spaces of the unit hit. Roll the dice in play. If the chosen model's DEF is equal to or less than the number of strikes rolled, it takes 1 damage point.",
    ],
    ["Force Field", "This model gain +1 DEF against blast attack."],
    ["Forward Observer", "Enemy models within two spaces of this model lose Cloak."],
    ["Fuel Depot", "If you are securing this building, allied models gain +1 SPD."],
    [
        "G.U.A.R.D. Base",
        "Once per turn, if you are securing one or more buildings with G.U.A.R.D. Base and spawn a G.U.A.R.D. unit, reduce its cost by 1.",
    ],
    [
        "Grappler",
        "Enemy models cannot move through this model or models adjacent to it. Enemy models are not immune to hazards adjacent to this model.",
    ],
    [
        "Guerrilla Tactics",
        "Allied Faction units gain Indirect Fire while within 3 spaces of this model.",
    ],
    ["High Density", "This building is not limited to four per player."],
    [
        "High Impact",
        "While this model is in play, allied Faction units gain +1 Boost Die when participating in blast attacks.",
    ],
    [
        "High Mobility",
        "This model can move through other models and treats all terrain as open terrain. This model is immune to hazards except when it ends its advancement on a hazard, but it still suffers all effects as a result of colliding with hazards and other models. A unit with High Mobility cannot end its movement on impassible terrain.",
    ],
    [
        "High Occupancy",
        "If a non-mechanical monster destroys this model with a Brawl attack, after the attack has been resolved restore one point of health to the monster.",
    ],
    [
        "Hit & Run",
        "If this model hits a target model with this attack, immediately after the attack is resolved advance this model up to 3 spaces even if this model has already advanced this turn.",
    ],
    ["Incombustable", "If this building is destroyed, replace it with rubble."],
    [
        "Incubator",
        "When this model is destroyed, if the space is unoccupied, immediately replace it with a Faction model from your reserves that does not have the Incubator special rule.",
    ],
    ["Indirect Fire", "This attack ignores Cover."],
    [
        "Intel",
        "While you are securing this building, enemy models lose Cloak and cannot gain it.",
    ],
    [
        "Intensify",
        "If this model is holding an objective space, other allied models within two spaces of it gain +1 Boost Die when participating in a brawl or blast attack.",
    ],
    [
        "Jam",
        "Enemy models and buildings your opponent has secured cannot use Actions while within two spaces of this model.",
    ],
    [
        "Lightning Attack",
        "This model can make a brawl attack in addition to any other attacks it makes during each of its activations.",
    ],
    ["Lone Wolf", "This model cannot participate in combined attacks."],
    [
        "Lords of Cthul Base",
        "Once per turn, if you are securing one or more buildings with Lords of Cthul Base and spawn a Lords of Cthul unit, reduce its cost by 1.",
    ],
    [
        "Manufacture",
        "If this attack hits an enemy unit, immediately after the attack has been resolved replace the enemy unit hit with a Faction unit from your unit reserves. The replacing Faction unit cannot participate in an attack this activation.",
    ],
    [
        "Martian Menace Base",
        "Once per turn, if you are securing one or more buildings with Martian Menace Base and spawn a Martian Menace unit, reduce its cost by 1.",
    ],
    ["Mechanical", "This monster is mechanical."],
    [
        "Motivator",
        "Other allied models that begin their advance within two spaces of this model gain +1 SPD.",
    ],
    [
        "Multi-Fire",
        "After this model resolves a blast attack, it can immediately make a blast attack with the dice in play against another enemy model. This model can make two additional attacks in this way. This model cannot make a  blast attack against the same model more than once in the same activation.",
    ],
    [
        "Munch",
        "If this monster destroys a unit with this attack, after the attack is resolved restore one point of health to this monster.",
    ],
    [
        "Opportunity",
        "If you are securing this building, you can use each Action twice during each of your turns. However, each of your models can still perform only one Action each activation.",
    ],
    [
        "Penetrator",
        "When resolving this attack, the target model suffers -1 DEF, to a minimum of 1.",
    ],
    [
        "Planet Eaters Base",
        "Once per turn, if you are securing one or more buildings with Planet Eaters Base and spawn a Planet Eaters unit, reduce its cost by 1.",
    ],
    [
        "Power Converter",
        "Once per turn, if you are securing one or more buildings with Power Converter and one of you attacks destroys an enemy model, you gain one additional power die.",
    ],
    [
        "Power Drain",
        "If this attack hits an enemy monster, the monster's controller loses one Power Dice.",
    ],
    [
        "Power Gorge",
        "When this attack destroys an enemy model, you gain an additional Power Die.",
    ],
    [
        "Power Hitter",
        "This model can spend one Power Die when participating in an attack. If it does, this attack does not generate any Power Dice.",
    ],
    [
        "Power Producer",
        "If you are securing one or more buildings with Power Producer when you Power Up, you gain one additional Power Die.",
    ],
    [
        "Radar Network",
        "If you are securing this building, allied models not affected by Radar gain +1 RNG to their blast attacks.",
    ],
    [
        "Rapid Fire",
        "This model can make a blast attack in addition to any other attack it makes during each of it's Activations.",
    ],
    [
        "Reach",
        "This model can make a brawl attack targeting any model within two spaces. This model can participate in combined brawl attacks against models within two spaces.",
    ],
    [
        "Reposition",
        "If this model is hit by an attack, after the attack is resolved this model can advance up to one space in any direction.",
    ],
    ["Resilience", "This monster is immune to Super Damage."],
    [
        "Resource Domination",
        "Once per turn, if you are securing one or more buildings with Resource Domination when you roll two or more Power Dice on an attack made by your monster and the attack hits an enemy model, after the attack is resolved, you can move one Power Die from your Dice Well to your Power Pool.",
    ],
    [
        "Return Fire",
        "When this model is missed by a blast attack, it can immediately make a blast attack with the dice in play.",
    ],
    [
        "Riled",
        "When this model is damaged or destroyed by an enemy attack, you gain one Power Die.",
    ],
    [
        "Safeguard",
        "If you are securing one or more buildings when you Power Up, you gain one additional Power Die.",
    ],
    [
        "Security Building",
        "If you are securing this building, allied units adjacent to this building gain +1 Boost Die when participating in brawl or blast attacks.",
    ],
    [
        "Seismic Step",
        "Once during each of your Monster Activations, if this model makes a stomp power attack, immediately after the attack is resolved it can move up to one space and make another stomp power attack with the dice in play.",
    ],
    [
        "Self-Destruct",
        "If this unit hits an enemy model with an attack, after the attack is resolved move this unit to your unit reserves.",
    ],
    ["Shadow Field", "While adjacent to this model, allied units gain Cloak."],
    [
        "Shadow Screen",
        "Models do not roll Boost Dice when participating in blast attacks targeting this model or units B2B with it.",
    ],
    [
        "Shadow Sun Syndicate Base",
        "Once per turn, if you are securing one or more buildings with Shadow Sun Syndicate Base and spawn a Shadow Sun Syndicate unit, reduce its cost by 1.",
    ],
    [
        "Shield Resonance",
        "While adjacent to this model, allied Faction units gain Force Field.",
    ],
    [
        "Side Step",
        "If this model is missed by an attack, after the attack is resolved this model can advance up to three spaces.",
    ],
    [
        "Siphon",
        "If this attack hits an enemy monster, you gain one Power Die. That monster's controller loses one Power Die.",
    ],
    [
        "Slingshot",
        "When this model performs a swat power attack or used the Fling trigger, the second target can be up to seven spaces away instead of five.",
    ],
    ["Spire", "A monster colliding with this building suffers +1 collision damage."],
    [
        "Spotter",
        "Enemy models within two spaces of this model have their DEF reduced by 1 against blast atatcks made by allied models, to a minimum of 1.",
    ],
    ["Stampede", "While this model is in play, allied Faction units gain +1 SPD."],
    [
        "Steady",
        "Enemy monsters do not roll Boost Dice when making body slam power attacks against this model.",
    ],
    [
        "Strip Mining",
        "While this model is in play, allied Faction units' brawl attacks gain the Destabilizer special rule.",
    ],
    [
        "Tactical Command",
        "While this model is in play, allied Faction units' blast attacks gain the Hit & Run special rule.",
    ],
    [
        "Tantrum",
        "When this model is hit by a body slam or throw power attack, after the attack is resolved you can move this monster up to two spaces, then return all non-Faction units adjacent to this monster to their unit reserves.",
    ],
    [
        "Terrasaurs Base",
        "Once per turn, if you are securing one or more buildings with Terrasaurs Base and spawn a Terrasaurs unit, reduce its cost by 1.",
    ],
    [
        "Terrify",
        "While adjacent to this model, enemy units cannot roll Boost Dice in their attacks.",
    ],
    [
        "Trade Policy",
        "When you Power Up, if you are securing this building, your opponent loses one Power Die.",
    ],
    [
        "Tunneler",
        "Other allied models that begin an advance within two spaces of this model gain High Mobility during that advance.",
    ],
    [
        "Underground Network",
        "If you are securing this building, when an allied unit advances while base to base with this building it may treat any spaces adjacent to any building with Underground Network or adjacent to any allied model with Teleport as adjacent spaces.",
    ],
    ["Unearthly Rage", "When this model is in play, other allied models gain Riled."],
    [
        "Unstable",
        "If this unit is hit by an attack, return all enemy units adjacent to it to their unit reserves, then this unit is destroyed.",
    ],
    [
        "Vampirism",
        "If this attack hits an enemy monster, restore 1 Health to this monster after this attack has been resolved.",
    ],
    [
        "Vantage Point",
        "If you are securing this building, blast attack made by allied units adjacent to this building ignore cover.",
    ],
    [
        "Waterlogged",
        "When this model advances onto a debris tile that is a hazard, flip it to\nthe rubble side.",
    ],
    ["Weapon Master", "This attack does Super Damage."],
    ["Windup", "This monster's swat and throw power attacks do Super Damage"],
    [
        "Wing Leader",
        "While this model is in play, allied Faction units with the Flight special rule gain +1 Boost Die when participating in blast attacks.",
    ],
]
